apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e-commerce-backend-app.fullname" . }}
  labels:
    app: {{ include "e-commerce-backend-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "e-commerce-backend-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "e-commerce-backend-app.name" . }}
    spec:
      serviceAccountName: {{ include "e-commerce-backend-app.fullname" . }}
      containers:
        - name: {{ include "e-commerce-backend-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: {{ .Values.env.env }}
            - name: APP_NAME
              value: {{ .Values.env.appName }}
            - name: KINESIS_STREAM_NAME
              value: {{ .Values.env.kinesisStreamName }}
            - name: AWS_REGION
              value: {{ .Values.env.awsRegion }}
            - name: VERSION
              value: {{ .Values.image.tag }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
