apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "e-commerce-backend-app.fullname" .) .Values.serviceAccount.name }}
  labels:
    app: {{ include "e-commerce-backend-app.name" . }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
    {{- end }}
