replicaCount: 1

image:
  # Replace with your AWS ECR repository URI
  repository: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/e-commerce-backend-app
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

env:
  env: "dev"
  appName: "e-commerce"
  kinesisStreamName: "e-commerce-dev-stream"
  awsRegion: "us-east-1"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  publicSubnets:
    - "subnet-xxx"
    - "subnet-yyy"

ingress:
  enabled: false
  host: ""
  annotations: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

eks:
  clusterName: ""
  clusterEndpoint: ""

lb:
  loadBalancerDNSName: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
