replicaCount: 1

serviceAccount:
  # Override default name by setting this (e.g. --set serviceAccount.name=my-custom-sa)
  name: ""
  # Set this to the IAM Role ARN (e.g. --set serviceAccount.roleArn=arn:aws:iam::<ACCOUNT_ID>:role/<YOUR_EKS_KINESIS_ACCESS_ROLE>)
  roleArn: ""

image:
  # Replace with your AWS ECR repository URI
  repository: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/e-commerce-backend-app
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000

ingress:
  enabled: false
  host: ""
  annotations: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
